// <auto-generated />
using DontMergeMeYet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DontMergeMeYet.Migrations
{
    [DbContext(typeof(InstallationContext))]
    [Migration("20180318234302_InitialSchema")]
    partial class InitialSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DontMergeMeYet.Data.RepositoryInstallation", b =>
                {
                    b.Property<int>("RepositoryId");

                    b.Property<DateTime>("InstallationDate");

                    b.Property<int>("InstallationId");

                    b.Property<string>("RepositoryFullName");

                    b.HasKey("RepositoryId");

                    b.HasIndex("InstallationId");

                    b.ToTable("RepositoryInstallations");
                });
#pragma warning restore 612, 618
        }
    }
}
